"""File storage behind an interface: local disk today, object storage later.

Keys are opaque paths such as `cv/2026/10/<uuid>.pdf`. Callers keep the key and
metadata in their own tables; this layer only stores bytes.
"""

from __future__ import annotations

import asyncio
import uuid
from pathlib import Path
from typing import Protocol

from app.core.clock import utcnow
from app.core.config import get_settings
from app.core.errors import NotFoundError


class Storage(Protocol):
    async def save(self, data: bytes, *, folder: str, suffix: str) -> str: ...
    async def read(self, key: str) -> bytes: ...
    async def delete(self, key: str) -> None: ...


class LocalStorage:
    def __init__(self, root: str | Path) -> None:
        self.root = Path(root)

    def _path(self, key: str) -> Path:
        path = (self.root / key).resolve()
        # Keys are generated by us, but never let one escape the storage root.
        if self.root.resolve() not in path.parents:
            raise NotFoundError("File not found.")
        return path

    async def save(self, data: bytes, *, folder: str, suffix: str) -> str:
        now = utcnow()
        safe_suffix = "".join(ch for ch in suffix.lower() if ch.isalnum())[:8]
        key = f"{folder}/{now:%Y/%m}/{uuid.uuid4().hex}.{safe_suffix or 'bin'}"
        path = self._path(key)

        def _write() -> None:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)

        await asyncio.to_thread(_write)
        return key

    async def read(self, key: str) -> bytes:
        path = self._path(key)
        if not path.is_file():
            raise NotFoundError("File not found.")
        return await asyncio.to_thread(path.read_bytes)

    async def delete(self, key: str) -> None:
        path = self._path(key)
        await asyncio.to_thread(path.unlink, missing_ok=True)


_storage: Storage | None = None


def get_storage() -> Storage:
    global _storage
    if _storage is None:
        _storage = LocalStorage(get_settings().storage_dir)
    return _storage


def set_storage(storage: Storage | None) -> None:
    global _storage
    _storage = storage
