"""cv studio

Revision ID: 92ce0e47d9fa
Revises: 9706984cfa1e
Create Date: 2026-10-04 10:23:00.153559
"""

from collections.abc import Sequence

import sqlalchemy as sa
import pgvector.sqlalchemy
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '92ce0e47d9fa'
down_revision: str | None = '9706984cfa1e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cvs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('template', sa.String(length=20), nullable=False),
    sa.Column('accent', sa.String(length=16), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('previous_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('last_action', sa.String(length=300), nullable=True),
    sa.Column('last_check', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('visibility', sa.String(length=8), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('og_key', sa.String(length=200), nullable=True),
    sa.Column('og_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cvs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cvs')),
    sa.UniqueConstraint('user_id', name=op.f('uq_cvs_user_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cvs')
    # ### end Alembic commands ###
