"""jobs, briefs, matches and profile vectors

Revision ID: 73023af52303
Revises: 327f59fa7b26
Create Date: 2026-10-04 16:02:06.669198
"""

from collections.abc import Sequence

import sqlalchemy as sa
import pgvector.sqlalchemy
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '73023af52303'
down_revision: str | None = '327f59fa7b26'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('company', sa.String(length=300), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('work_mode', sa.String(length=16), nullable=True),
    sa.Column('employment_type', sa.String(length=32), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_text', sa.String(length=64), nullable=True),
    sa.Column('salary_text', sa.String(length=200), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('company_logo', sa.String(length=600), nullable=True),
    sa.Column('fingerprint', sa.String(length=600), nullable=False),
    sa.Column('description_text', sa.Text(), nullable=True),
    sa.Column('detail_status', sa.String(length=16), nullable=False),
    sa.Column('detail_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applicants', sa.String(length=64), nullable=True),
    sa.Column('industries', sa.String(length=300), nullable=True),
    sa.Column('source_seniority', sa.String(length=64), nullable=True),
    sa.Column('insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('insights_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('source', 'external_id', name='uq_jobs_source_external_id')
    )
    op.create_index('ix_jobs_embedding', 'jobs', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_jobs_fingerprint'), 'jobs', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_jobs_posted_at'), 'jobs', ['posted_at'], unique=False)
    op.create_table('briefs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('emailed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_briefs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_briefs'))
    )
    op.create_index('ix_briefs_user_created', 'briefs', ['user_id', 'created_at'], unique=False)
    op.create_table('matches',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('brief_id', sa.UUID(), nullable=True),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('parts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('review', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['briefs.id'], name=op.f('fk_matches_brief_id_briefs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_matches_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_matches_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches')),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_matches_user_job')
    )
    op.create_index(op.f('ix_matches_brief_id'), 'matches', ['brief_id'], unique=False)
    op.create_index('ix_matches_user_status_created', 'matches', ['user_id', 'status', 'created_at'], unique=False)
    op.add_column('profiles', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True))
    op.add_column('profiles', sa.Column('embedded_version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'embedded_version')
    op.drop_column('profiles', 'embedding')
    op.drop_index('ix_matches_user_status_created', table_name='matches')
    op.drop_index(op.f('ix_matches_brief_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index('ix_briefs_user_created', table_name='briefs')
    op.drop_table('briefs')
    op.drop_index(op.f('ix_jobs_posted_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_fingerprint'), table_name='jobs')
    op.drop_index('ix_jobs_embedding', table_name='jobs', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('jobs')
    # ### end Alembic commands ###
