"""admin ai controls

Revision ID: e3dc9301da00
Revises: 7b2e9c1d4a55
Create Date: 2026-10-04 13:05:51.828738
"""

from collections.abc import Sequence

import sqlalchemy as sa
import pgvector.sqlalchemy
from alembic import op


revision: str = 'e3dc9301da00'
down_revision: str | None = '7b2e9c1d4a55'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ai_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('ai_daily_budget', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ai_daily_budget')
    op.drop_column('users', 'ai_enabled')
    # ### end Alembic commands ###
