"""application kits

Revision ID: 6cb5930daa5e
Revises: 73023af52303
Create Date: 2026-10-04 16:24:41.298406
"""

from collections.abc import Sequence

import sqlalchemy as sa
import pgvector.sqlalchemy
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '6cb5930daa5e'
down_revision: str | None = '73023af52303'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kits',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=4), nullable=False),
    sa.Column('tone', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('resume', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cover_letter', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extras', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fact_check', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_kits_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_kits_match_id_matches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_kits_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kits')),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_kits_user_job')
    )
    op.create_index(op.f('ix_kits_user_id'), 'kits', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kits_user_id'), table_name='kits')
    op.drop_table('kits')
    # ### end Alembic commands ###
