"""radars and source runs

Revision ID: 327f59fa7b26
Revises: 796a94fc6793
Create Date: 2026-10-04 15:29:48.646691
"""

from collections.abc import Sequence

import sqlalchemy as sa
import pgvector.sqlalchemy
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '327f59fa7b26'
down_revision: str | None = '796a94fc6793'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_runs',
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('query', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('results', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_runs'))
    )
    op.create_index(op.f('ix_source_runs_created_at'), 'source_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_source_runs_source'), 'source_runs', ['source'], unique=False)
    op.create_table('radars',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('next_brief_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_radars_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_radars')),
    sa.UniqueConstraint('user_id', name=op.f('uq_radars_user_id'))
    )
    op.create_index(op.f('ix_radars_next_brief_at'), 'radars', ['next_brief_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_radars_next_brief_at'), table_name='radars')
    op.drop_table('radars')
    op.drop_index(op.f('ix_source_runs_source'), table_name='source_runs')
    op.drop_index(op.f('ix_source_runs_created_at'), table_name='source_runs')
    op.drop_table('source_runs')
    # ### end Alembic commands ###
