"""images and public profiles

Revision ID: 9706984cfa1e
Revises: 367b1133450b
Create Date: 2026-10-04 09:42:36.664892
"""

from collections.abc import Sequence

import sqlalchemy as sa
import pgvector.sqlalchemy
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '9706984cfa1e'
down_revision: str | None = '367b1133450b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_images_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_images'))
    )
    op.create_index('ix_images_user', 'images', ['user_id'], unique=False)
    op.create_table('public_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('visibility', sa.String(length=8), nullable=False),
    sa.Column('template', sa.String(length=20), nullable=False),
    sa.Column('appearance', sa.String(length=8), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('og_key', sa.String(length=200), nullable=True),
    sa.Column('og_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_public_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_public_profiles')),
    sa.UniqueConstraint('slug', name=op.f('uq_public_profiles_slug')),
    sa.UniqueConstraint('user_id', name=op.f('uq_public_profiles_user_id'))
    )
    op.create_table('public_profile_views',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['public_profiles.id'], name=op.f('fk_public_profile_views_profile_id_public_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'day', name=op.f('pk_public_profile_views'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('public_profile_views')
    op.drop_table('public_profiles')
    op.drop_index('ix_images_user', table_name='images')
    op.drop_table('images')
    # ### end Alembic commands ###
