"""tracker and momentum

Revision ID: 3f6d5c4b17a3
Revises: 44d0390698bb
Create Date: 2026-10-04 12:02:57.020140
"""

from collections.abc import Sequence

import sqlalchemy as sa
import pgvector.sqlalchemy
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '3f6d5c4b17a3'
down_revision: str | None = '44d0390698bb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_days',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activity_days_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'day', name=op.f('pk_activity_days'))
    )
    op.create_table('goals',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('weekly_applications', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_goals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_goals'))
    )
    op.create_table('applications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=True),
    sa.Column('kit_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('furthest', sa.Integer(), nullable=False),
    sa.Column('stage_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_step', sa.String(length=120), nullable=True),
    sa.Column('next_step_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('contact_email', sa.String(length=254), nullable=True),
    sa.Column('follow_up_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nudged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('followed_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('follow_up_draft', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_applications_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], name=op.f('fk_applications_kit_id_kits'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_applications_match_id_matches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_applications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_applications_user_job')
    )
    op.create_index(op.f('ix_applications_applied_at'), 'applications', ['applied_at'], unique=False)
    op.create_index(op.f('ix_applications_follow_up_due_at'), 'applications', ['follow_up_due_at'], unique=False)
    op.create_index(op.f('ix_applications_next_step_at'), 'applications', ['next_step_at'], unique=False)
    op.create_index('ix_applications_user_stage', 'applications', ['user_id', 'stage', 'position'], unique=False)
    op.create_table('application_events',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_events_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_events'))
    )
    op.create_index('ix_application_events_app_at', 'application_events', ['application_id', 'at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_application_events_app_at', table_name='application_events')
    op.drop_table('application_events')
    op.drop_index('ix_applications_user_stage', table_name='applications')
    op.drop_index(op.f('ix_applications_next_step_at'), table_name='applications')
    op.drop_index(op.f('ix_applications_follow_up_due_at'), table_name='applications')
    op.drop_index(op.f('ix_applications_applied_at'), table_name='applications')
    op.drop_table('applications')
    op.drop_table('goals')
    op.drop_table('activity_days')
    # ### end Alembic commands ###
